modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "nsp"
version = "${version}"
displayName = "OneShotMod-1.21.1"
authors = "Redstone233"
description = '''
[Multiple Loader]A simple one-hit kill module.
'''
#logoFile = ""

[[dependencies.nsp]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nsp]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nsp]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "nsp.mixins.json"
